on:
  workflow_call:

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from provider"
        shell: bash

      - uses: actions/checkout@v3

      - uses: ./some-action/